# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.rig_root] run return run \
	function animated_java:global/errors/function_not_executed_as_root_entity \
	with {'function_path': 'animated_java:test_blueprint/variants/green_snave/apply'}
# TODO Apply the variant to the rig here.
execute on passengers if entity @s[tag=aj.test_blueprint.bone.bone] run function animated_java:test_blueprint/variants/green_snave/zzz/2