# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Attempts to smoothly transition from the currently playing animation into this one.
#ARGS: {duration: int, to_frame: int}
execute unless entity @s[type=item_display,tag=aj.armor_stand.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'function_path': 'animated_java:armor_stand/animations/exit_sit/tween_play'}
function animated_java:armor_stand/animations/pause_all
tag @s add aj.armor_stand.animation.exit_sit.playing
$scoreboard players set @s aj.tween_duration $(duration)
$scoreboard players set @s aj.frame $(to_frame)
scoreboard players operation #this aj.i = @s aj.tween_duration
scoreboard players add @s aj.tween_duration 1
execute on passengers store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$function animated_java:armor_stand/animations/exit_sit/zzz/apply_frame {frame: $(to_frame)}