# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Sets the frame without interpolation
#ARGS: {frame: int}
$function animated_java:armor_stand/animations/think/zzz/frames/$(frame)
execute on passengers run data modify entity @s start_interpolation set value -1