# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Make this text fancier in the actual implementation.
$tellraw @a "The function $(function_path) must be executed as the root entity of the rig."