# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
kill @e[type=item_display,tag=aj.rig_entity]
tellraw @a "All Animated Java rigs have been removed from the world."