# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# This command will be added for each animation.
execute if entity @s[tag=aj.armor_stand.animation.walk.playing] run \
	function animated_java:armor_stand/animations/walk/zzz/on_tick