# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.rig_root] run return run \
	function animated_java:global/errors/function_not_executed_as_root_entity \
	{'function_path': 'animated_java:test_blueprint/variants/default/apply'}
execute on passengers if entity @s[tag=aj.test_blueprint.bone.locator] run function animated_java:test_blueprint/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.test_blueprint.bone.camera] run function animated_java:test_blueprint/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.test_blueprint.bone.bone] run function animated_java:test_blueprint/variants/default/zzz/6