# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Pauses all animations
function animated_java:armor_stand/animations/walk/pause
function animated_java:armor_stand/animations/jumping_jacks/pause
function animated_java:armor_stand/animations/think/pause
function animated_java:armor_stand/animations/enter_sit/pause
function animated_java:armor_stand/animations/sitting/pause
function animated_java:armor_stand/animations/exit_sit/pause