import './dialogs/about'
import './dialogs/animationProperties'
import './dialogs/boneConfig'
import './dialogs/changelog'
import './dialogs/exportProgress'
import './dialogs/item-display-config'
import './dialogs/locatorConfig'
import './dialogs/text-display-config'
import './dialogs/unexpectedError'
import './dialogs/vanillaBlockDisplayConfig'
import './dialogs/variantConfig'

import './panels/customKeyframe'
import './panels/textDisplayElement'
import './panels/vanillaBlockDisplayElement'
import './panels/vanillaItemDisplayElement'
import './panels/variants'

import './popups/animatedJavaLoading'
import './popups/blueprintLoading'
import './popups/incompatabilityPopup'
import './popups/installed'

import './animatedJavaBarItem'
import './dialogs/import-ajmodel'
import './keyframeEasings'
