import './dialogs/about'
import './dialogs/animation-properties'
import './dialogs/block-display-config'
import './dialogs/bone-config'
import './dialogs/changelog'
import './dialogs/export-progress'
import './dialogs/import-ajmodel'
import './dialogs/item-display-config'
import './dialogs/locator-config'
import './dialogs/text-display-config'
import './dialogs/unexpected-error'
import './dialogs/variant-config'

import './panels/block-display-element'
import './panels/custom-keyframe'
import './panels/item-display-element'
import './panels/text-display-element'
import './panels/variants'

import './popups/animated-java-loading'
import './popups/blueprint-loading'
import './popups/incompatability'
import './popups/installed'

import './animatedJavaBarItem'
import './keyframeEasings'
