name: 🐛 Bug Report
description: Report a problem or bug you encountered while using Animated Java
body:
    - type: markdown
      attributes:
          value: |
              Please fill out the sections below to help us reproduce and fix the issue you encountered.
    - type: input
      id: title
      attributes:
          label: Issue Title
          description: A clear and concise title that describes the issue you encountered.
          placeholder: Enter the issue title here
      validations:
          required: true
