# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# This command will be added for each animation.
execute if entity @s[tag=aj.armor_stand.animation.walk.playing] run function animated_java:armor_stand/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.armor_stand.animation.jumping_jacks.playing] run function animated_java:armor_stand/animations/jumping_jacks/zzz/on_tick
execute if entity @s[tag=aj.armor_stand.animation.think.playing] run function animated_java:armor_stand/animations/think/zzz/on_tick
execute if entity @s[tag=aj.armor_stand.animation.enter_sit.playing] run function animated_java:armor_stand/animations/enter_sit/zzz/on_tick
execute if entity @s[tag=aj.armor_stand.animation.sitting.playing] run function animated_java:armor_stand/animations/sitting/zzz/on_tick
execute if entity @s[tag=aj.armor_stand.animation.exit_sit.playing] run function animated_java:armor_stand/animations/exit_sit/zzz/on_tick