# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# It's actually faster to use a single command like this than to spread it into a function.
execute on passengers if entity @s[tag=aj.test_blueprint.bone.bone] run \
	data merge entity @s {transformation: [-1f,0f,1.2246467991473532e-16f,-0.4959999999999999f,0f,1f,0f,0.6960000000000002f,-1.2246467991473532e-16f,0f,-1f,-6.074248123770871e-17f,0f,0f,0f,1f], start_interpolation: 0}