# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.test_blueprint.bone.bone] run \
	data merge entity @s {transformation: [-1f,0f,1.2246467991473532e-16f,-0.6960000000000002f,0f,1f,0f,-0.07200000000000001f,-1.2246467991473532e-16f,0f,-1f,-8.52354172206558e-17f,0f,0f,0f,1f], start_interpolation: 0}