# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.armor_stand.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'function_path': 'animated_java:armor_stand/variants/no_armor/apply'}
execute on passengers if entity @s[tag=aj.armor_stand.bone.baseplate_pivot_a] run function animated_java:armor_stand/variants/no_armor/zzz/0
execute on passengers if entity @s[tag=aj.armor_stand.bone.head] run function animated_java:armor_stand/variants/no_armor/zzz/1
execute on passengers if entity @s[tag=aj.armor_stand.bone.left_arm] run function animated_java:armor_stand/variants/no_armor/zzz/2
execute on passengers if entity @s[tag=aj.armor_stand.bone.right_arm] run function animated_java:armor_stand/variants/no_armor/zzz/3
execute on passengers if entity @s[tag=aj.armor_stand.bone.body] run function animated_java:armor_stand/variants/no_armor/zzz/4
execute on passengers if entity @s[tag=aj.armor_stand.bone.right_leg2] run function animated_java:armor_stand/variants/no_armor/zzz/5
execute on passengers if entity @s[tag=aj.armor_stand.bone.left_leg] run function animated_java:armor_stand/variants/no_armor/zzz/6