import { Compiler, VariableMap } from 'mc-build/mcl/Compiler'
import { Parser } from 'mc-build/mcl/Parser'
import { TemplateRegisterer } from 'mc-build/mcl/TemplateRegisterer'
import { Tokenizer } from 'mc-build/mcl/TokenizerImpl'
import { getMisodeVersion } from '../minecraft/versionManager'
import type { ExportedFile } from '../util'

interface CompilerOptions {
	sourceFiles: Record<string, string>
	destPath: string
	variables: Record<string, any>
	version: string
	exportedFiles: Map<string, ExportedFile>
}

export async function compileMcbProject({
	sourceFiles,
	destPath,
	variables,
	version,
	exportedFiles,
}: CompilerOptions) {
	console.group('Compiling', sourceFiles)
	console.log('Variables:', variables)

	TemplateRegisterer.register()

	const misodeVersionData = await getMisodeVersion(version)

	const compiler = new Compiler('src', {
		libDir: null,
		generatedDirName: 'zzz',
		internalScoreboardName: 'aj.i',
		eqVarScoreboardName: null,
		eqConstScoreboardName: null,
		header: '# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.',
		ioThreadCount: null,
		dontEmitComments: true,
		setup: null,
		formatVersion: misodeVersionData.data_pack_version,
	})
	compiler.disableRequire = true

	compiler.io = {
		cleanup: () => undefined,
		finished: () => true,
		write: (localPath, content) => {
			const writePath = PathModule.join(destPath, localPath)
			exportedFiles.set(writePath, {
				content,
				includeInAJMeta: true,
			})
		},
	}

	console.time('MC-Build compiled in')

	const mcbTemplateFiles = Object.entries(sourceFiles).filter(([path]) => path.endsWith('.mcbt'))
	const mcbFiles = Object.entries(sourceFiles).filter(([path]) => path.endsWith('.mcb'))

	for (const [path, mcbFile] of mcbTemplateFiles) {
		try {
			compiler.addFile(path, Parser.parseMcbtFile(Tokenizer.tokenize(mcbFile, path)))
		} catch (e) {
			if (e instanceof Error) e.message = `Failed to compile "${path}":\n\t${e.message}`
			throw e
		}
	}

	for (const [path, mcbFile] of mcbFiles) {
		try {
			compiler.addFile(path, Parser.parseMcbFile(Tokenizer.tokenize(mcbFile, path)))
		} catch (e) {
			if (e instanceof Error) e.message = `Failed to compile "${path}":\n\t${e.message}`
			throw e
		}
	}

	compiler.compile(VariableMap.fromObject(variables))
	console.timeEnd('MC-Build compiled in')
	console.log('Exported files:', exportedFiles.keys())
	console.groupEnd()

	return exportedFiles
}
