# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:global/root/on_tick