# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# TODO Figure out how this will work.
# It will probably involve killing the existing bones, and re-summoning them, then applying the default NBT to the root entity?
# This probably won't work in cases where custom NBT is removed from the root between exports.