# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# This command will be added for each animation.
execute if entity @s[tag=aj.test_blueprint.animation.anim1.playing] run \
	function animated_java:test_blueprint/animations/anim1/zzz/on_tick
execute if entity @s[tag=aj.test_blueprint.animation.anim2.playing] run \
	function animated_java:test_blueprint/animations/anim2/zzz/on_tick