# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
#Args: {args:{variant: string, animation: string, frame: int, start_animation: boolean}}
# frame is ignored unless animation is specified.
data modify storage aj:temp args set value {variant:'', animation:'', frame: 0}
$execute store success score #success aj.i run data modify storage aj:temp args set value $(args)
summon minecraft:item_display ~ ~ ~ { \
	teleport_duration: 1, \
	interpolation_duration: 1, \
	Tags:['aj.new','aj.rig_entity','aj.rig_root','aj.test_blueprint.root'], \
	Passengers:[{id:"minecraft:item_display",Tags:["aj.new","aj.rig_entity","aj.locator","aj.test_blueprint.locator","aj.test_blueprint.locator.locator"]},{id:"minecraft:item_display",Tags:["aj.new","aj.rig_entity","aj.camera","aj.test_blueprint.camera","aj.test_blueprint.camera.camera"]},{id:"minecraft:item_display",Tags:["aj.new","aj.rig_entity","aj.bone","aj.test_blueprint.bone","aj.test_blueprint.bone.bone"],transformation:[-1f,0f,1.2246467991473532e-16f,0f,0f,1f,0f,0f,-1.2246467991473532e-16f,0f,-1f,0f,0f,0f,0f,1f],interpolation_duration:1,teleport_duration:1,item_display:"head",item:{id:"minecraft:white_dye",count:1,components:{"minecraft:custom_model_data":23}},glow_color_override:"#ff0000",height:100f,width:100f}] \
	}
execute as @e[type=item_display,tag=aj.new,limit=1,distance=..0.01] run function animated_java:test_blueprint/zzz/24