# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
tag @s remove aj.new
data modify storage aj:temp args set value {variant:'', animation:'', frame: 0}
$execute store success score #success aj.i run data modify storage aj:temp args set value $(args)
# Variant Arguement
execute if data storage aj:temp args.variant run function animated_java:test_blueprint2/zzz/10
# Animation, Frame, and Start Animation Arguments
execute if data storage aj:temp args.animation run function animated_java:test_blueprint2/zzz/23
# Custom Summon Commands
say Hello World!
tellraw @a "I was summoned!"
# Custom Summon Commands
# Run the on_summon function for the root entity.
function #animated_java:test_blueprint2/as_root/on_summon