# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
#ARGS: {frame: int}
$function animated_java:test_blueprint/animations/anim2/zzz/frames/$(frame)