import { Parser, SyncIo, Tokenizer } from 'mc-build'
import { Compiler, VariableMap } from 'mc-build/dist/mcl/Compiler'
import { getDataPackFormat } from '../../util/minecraftUtil'
import { type MinecraftVersion } from '../global'
import { type ExportedFile } from '../util'

interface CompilerOptions {
	path: string
	mcbFile: string
	destPath: string
	variables: Record<string, any>
	version: MinecraftVersion
	exportedFiles: Map<string, ExportedFile>
}

export function compile({
	path,
	mcbFile,
	destPath,
	variables,
	version,
	exportedFiles,
}: CompilerOptions) {
	console.group('Compiling', path)
	console.log('Variables:', variables)

	const compiler = new Compiler('src/', {
		libDir: null,
		generatedDirName: 'zzz',
		internalScoreboardName: 'aj.i',
		eqVarScoreboardName: null,
		eqConstScoreboardName: null,
		header: '# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.',
		ioThreadCount: null,
		dontEmitComments: true,
		setup: null,
		formatVersion: getDataPackFormat(version),
	})
	compiler.disableRequire = true
	compiler.templateParsingEnabled = false

	function createSyncIO() {
		const io = new SyncIo()
		io.write = (localPath, content) => {
			const writePath = PathModule.join(destPath, localPath)
			exportedFiles.set(writePath, {
				content,
				includeInAJMeta: true,
			})
		}
		return io
	}
	compiler.io = createSyncIO()

	console.time('MC-Build compiled in')
	const tokens = Tokenizer.tokenize(mcbFile, path)
	compiler.addFile(path, Parser.parseMcbFile(tokens))
	compiler.compile(VariableMap.fromObject(variables))
	console.timeEnd('MC-Build compiled in')
	console.log('Exported files:', exportedFiles.keys())
	console.groupEnd()

	return exportedFiles
}
