# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# It's actually faster to use a single command like this than to spread it into a function.
execute on passengers if entity @s[tag=aj.test_blueprint.bone.bone] run \
	data merge entity @s {transformation: [-1.2377641290737884f,0f,1.5158238787696264e-16f,0f,0f,0.7622358709262116f,0f,0.09656781074217094f,-1.5158238787696264e-16f,0f,-1.2377641290737884f,0f,0f,0f,0f,1f], start_interpolation: 0}