# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# It's actually faster to use a single command like this than to spread it into a function.
execute on passengers if entity @s[tag=aj.test_blueprint.bone.bone] run \
	data merge entity @s {transformation: [-0.8530536869268817f,0f,1.044689467195854e-16f,0f,0f,1.1469463130731183f,0f,-0.252817810742171f,-1.044689467195854e-16f,0f,-0.8530536869268817f,0f,0f,0f,0f,1f], start_interpolation: 0}