# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# This command will be added for each animation.
execute if entity @s[tag=aj.test_blueprint2.animation.anim1.playing] run \
	function *test_blueprint2/animations/anim1/on_tick
execute if entity @s[tag=aj.test_blueprint2.animation.anim2.playing] run \
	function *test_blueprint2/animations/anim2/on_tick