# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
tag @s remove aj.new
# Variant Arguement
execute if data storage aj:temp args.variant run function animated_java:armor_stand/zzz/1 with storage aj:temp args
# Animation, Frame, and Start Animation Arguments
execute unless data storage aj:temp args.animation run return run function animated_java:armor_stand/set_default_pose
execute if data storage aj:temp args.animation run function animated_java:armor_stand/zzz/5 with storage aj:temp args
# Custom Summon Commands

# Custom Summon Commands
# Run the on_summon function for the root entity.
function #animated_java:armor_stand/as_root/on_summon