# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if data storage aj:temp {args:{animation:''}} run return run tellraw @a "The animation argument cannot be an empty string."
execute store result score #frame aj.i run data get storage aj:temp args.frame
execute if score #frame aj.i matches ..-1 run return run tellraw @a "The frame argument must be a non-negative integer."
execute store result storage aj:temp args.frame int 1 run scoreboard players get #frame aj.i
# Attempt to apply the animation frame, if it fails, print an error.
execute store success score #success aj.i run function animated_java:armor_stand/zzz/19 with storage aj:temp args
$execute unless score #success aj.i matches 1 run return run tellraw @a "The animation $(animation) does not exist."
execute if data storage aj:temp {args:{start_animation: true}} run function animated_java:armor_stand/zzz/22 with storage aj:temp args