# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if data storage aj:temp {args:{animation:''}} run return run function animated_java:armor_stand/zzz/6
execute store result score #frame aj.i run data get storage aj:temp args.frame
execute if score #frame aj.i matches ..-1 run return run function animated_java:armor_stand/zzz/7
# The frame list is 1-indexed, so we need to add 1 to the frame argument.
execute store result storage aj:temp args.frame int 1 run scoreboard players add #frame aj.i 1
# Attempt to apply the animation frame, if it fails, print an error.
execute store success score #success aj.i run function animated_java:armor_stand/zzz/8 with storage aj:temp args
execute unless score #success aj.i matches 1 run return run function animated_java:armor_stand/zzz/9 with storage aj:temp args
execute if data storage aj:temp {args:{start_animation: 1b}} run function animated_java:armor_stand/zzz/10 with storage aj:temp args