# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tellraw @a ["",[{"text":"[","color":"gray"},{"text":"AJ","color":"aqua"},{"text":"] "}],{"text":"Error: ","color":"red"},{"text":"animation","color":"yellow"},{"text":" cannot be an empty string.","color":"red"}]
function animated_java:armor_stand/remove/this